apiVersion: rikami.zagoapps.com/v1
kind: Profile
metadata:
  name: default
  namespace: dev
spec:
  # TODO(user): Add fields here
  gateway: dev-gateway
  pullPolicy: Always
  domain: pve.zagoapps.com
  externalSecretsConfig:
    refreshPolicy: CreatedOnce
    refreshInterval: 0s
    secretStoreRef:
      name: aws-ssm
      kind: ClusterSecretStore
  databaseConfig:
    appConfig:
      hostKey: host
      passwordKey: password
      usernameKey: username
      secretAppPath: /clusters/psql/dev/*/app
    migratorConfig:
      secretMigratorPath: /clusters/psql/dev/*/migrator
      secretKey: url
